{
 "title": "Unifi - Unifi Protect InfluxDB",
 "description": "Grafana Dashboard for Unifi Protect InfluxDB",
 "tags": [
  "unifi",
  "unifi protect",
  "protect"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "NVRName",
    "label": "Unifi Protect Host",
    "query": "SHOW TAG VALUES FROM unifi_protect_overview WITH KEY=protectname"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2021/02/unifiprotect.png\">\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 23, "x": 1, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Name: $tag_protectname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "protectname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unifi_protect_overview",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    },
    {
     "alias": "IP: $tag_protecthost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "protecthost" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unifi_protect_overview",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    },
    {
     "alias": "Mac: $tag_protectmac",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "protectmac" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unifi_protect_overview",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    },
    {
     "alias": "Firmware: $tag_protectfirmware",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "protectfirmware" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unifi_protect_overview",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    },
    {
     "alias": "Protect version: $tag_protectversion",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "protectversion" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unifi_protect_overview",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    },
    {
     "alias": "Disk: $tag_storage_model/$tag_storage_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storage_model" ], "type": "tag" },
      { "params": [ "storage_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unifi_protect_overview",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "stat",
   "description": "On this Panel, you can quickly know how much CPU your device is consuming.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "% CPU Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unifi_protect_overview",
     "select": [
      [
       { "params": [ "cpuavg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    }
   ]
  },
  {
   "title": "Historical CPU Consumption",
   "type": "graph",
   "description": "On this Panel, you can quickly know how much CPU your device is consuming.",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent", "label": "% CPU Consumption" }
   ],
   "targets": [
    {
     "alias": "% CPU Consumption",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unifi_protect_overview",
     "select": [
      [
       { "params": [ "cpuavg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    }
   ]
  },
  {
   "title": "Historical RAM Consumption",
   "type": "graph",
   "description": "On this Panel, you can quickly know how much Ram your device has been using.",
   "gridPos": { "h": 6, "w": 8, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent", "label": "% RAM Consumption" }
   ],
   "targets": [
    {
     "alias": "% RAM Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unifi_protect_overview",
     "query": "SELECT (last(\"mem_total\") - last(\"mem_available\")) * (100 / last(\"mem_total\")) FROM \"unifi_protect_overview\" WHERE (\"protectname\" =~ /^$NVRName$/) AND $timeFilter GROUP BY time($inter) fill(none)",
     "select": [
      [
       { "params": [ "mem_free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    }
   ]
  },
  {
   "title": "Historical  Temperature",
   "type": "graph",
   "description": "On this Panel, you can quickly know the temperature your device has been",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius", "label": "Device Temperature in Celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$inter" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unifi_protect_overview",
     "query": "SELECT (last(\"mem_total\") - last(\"mem_available\")) * (100 / last(\"mem_total\")) FROM \"unifi_protect_overview\" WHERE (\"protectname\" =~ /^$NVRName$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    }
   ]
  },
  {
   "title": "Current RAM Usage",
   "type": "stat",
   "description": "On this Panel, you can quickly know how much Ram your device has been using.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "% RAM Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unifi_protect_overview",
     "query": "SELECT (last(\"mem_total\") - last(\"mem_available\")) * (100 / last(\"mem_total\")) FROM \"unifi_protect_overview\" WHERE (\"protectname\" =~ /^$NVRName$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "mem_free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "stat",
   "description": "On this Panel, you can quickly know the temperature your device has been",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "unifi_protect_overview",
     "query": "SELECT (last(\"mem_total\") - last(\"mem_available\")) * (100 / last(\"mem_total\")) FROM \"unifi_protect_overview\" WHERE (\"protectname\" =~ /^$NVRName$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    }
   ]
  },
  { "title": "Camera List ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Unifi Protect Cameras",
   "type": "table",
   "description": "On this Panel, you can quickly list all your Unifi Cameras connected to $NVRName",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "cameraType" ], "type": "tag" },
      { "params": [ "cameraIP" ], "type": "tag" },
      { "params": [ "cameraName" ], "type": "tag" },
      { "params": [ "cameraMAC" ], "type": "tag" },
      { "params": [ "camerafirmware" ], "type": "tag" },
      { "params": [ "camerafwbuild" ], "type": "tag" }
     ],
     "measurement": "unifi_protect_cameras",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "camerastate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "cameraIP" ], "type": "tag" }
     ],
     "measurement": "unifi_protect_cameras",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "cameralastSeen" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last Seen" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "cameraIP" ], "type": "tag" }
     ],
     "measurement": "unifi_protect_cameras",
     "query": "SELECT last(\"VMSize\") AS \"VM  Size\" FROM \"veeam_azure_vm_unprotected\" WHERE (\"VMName\" =~ /^$VMName$/) AND $timeFilter GROUP BY \"VMName\", \"VMRegion\" ",
     "select": [
      [
       { "params": [ "cameraLAN" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Link State" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "protectname", "operator": "=~", "value": "/^$NVRName$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 15 },
   "options": {
    "content": "<a href=\"https://www.jorgedelacruz.es\"><img src=\"https://www.jorgedelacruz.es/wp-content/uploads/2019/04/jorgedelacruz-banner_2efede4ef704c939e63a3763231f5961.png\"></a>\n\n\n\n"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}